const SUPPORT_IMAGES = {
  reo: require('./supports/reo.jpg'),
  alistar: require('./supports/alistar.jpg'),
  alistar: require('./supports/ashe.jpg'),
  bard: require('./supports/bard.jpg'),
  blitz: require('./supports/blitz.png'),
  brand: require('./supports/brand.jpg'),
  braum: require('./supports/braum.jpg'),
  galio: require('./supports/galio.jpg'),
  janna: require('./supports/janna.jpg'),
  karma: require('./supports/karma.png'),
  leona: require('./supports/leona.jpg'),
  lulu: require('./supports/lulu.jpg'),
  lux: require('./supports/lux.jpg'),
  malphite: require('./supports/malphite.jpg'),
  maokai: require('./supports/maokai.jpg'),
  morgana: require('./supports/morgana.png'),
  pantheon: require('./supports/pantheon.png'),
  poppy: require('./supports/poppy.jpg'),
  pyke: require('./supports/pyke.jpg'),
  rakan: require('./supports/rakan.jpg'),
  renata: require('./supports/renata_glasc.jpg'),
  senna: require('./supports/senna.jpg'),
  sett: require('./supports/sett.jpg'),
  shen: require('./supports/shen.jpg'),
  sona: require('./supports/sona.jpg'),
  soraka: require('./supports/soraka.jpg'),
  swain: require('./supports/swain.png'),
  tahm: require('./supports/tahm_kench.jpg'),
  taric: require('./supports/taric.jpg'),
  teemo: require('./supports/teemo.jpg'),
  thresh: require('./supports/thresh.jpg'),
  veigar: require('./supports/veigar.jpg'),
  velkoz: require('./supports/velkoz.jpg'),
  xerath: require('./supports/xerath.jpg'),
  yumi: require('./supports/yumi.jpg'),
  zac: require('./supports/zac.jpg'),
  zilean: require('./supports/zilean.png'),
  zyra: require('./supports/zyra.jpg'),
}

export default SUPPORT_IMAGES;
